### PR TITLE
Add exception error code

### PR DESCRIPTION
**Pull request by mobinzk**
## Description
Add error code when we throw InvalidPaymentException.

## Motivation and context

This will allow users to  customise the error message using the error code and provide better user excperience based on that.

## How has this been tested?

I've tested the code and it doesn't effect the existing users.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [ ] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

**Comment by khanzadimahdi** [comment]
have you test it? it works correctly?

**Comment by mobinzk** [comment]
Yes, I always test the code :)

**Comment by khanzadimahdi** [comment]
thanks for your contribution.

**Comment by khanzadimahdi** [comment]
do you have access to paypal or stripe? in Iran i cant use their API.

can you create paypal or stripe driver? here is the list of drivers that would be awesome to be added in this package:

- stripe
- authorize
- 2checkout
- braintree
- skrill
- payU
- amazon payments
- wepay
- payoneer
- paysimple
- saderat
- pasargad

**Comment by mobinzk** [comment]
No problem, If find some free time I'll defiantly help with some of the other drivers.

**Pull request merged**
