### PR TITLE
Added RefID to invoices

### PR DESCRIPTION
**Pull request by AramZahedi**
## Description

Added RefID property to invoice. Some drivers now set RefID to invoice after payment.

### CODE REVIEW

**Comment by khanzadimahdi** [comment]
what is refid and how can we use it? what's the benefit of adding it into the invoice?

**Comment by khanzadimahdi** [comment]
tell me the benefit of keeping `refid` in invoices, then i will merge it.

**Comment by AramZahedi** [comment]
> tell me the benefit of keeping `refid` in invoices, then i will merge it.

RefID is the tracking code of banks, not the gateway.
It will be useful in some cases that gateways cannot track the payment so payer can track their payment using RefID.

**Comment by khanzadimahdi** [comment]
you mean we use `refId` after the payment has done? its a kind of `receipt` ?

**Comment by AramZahedi** [comment]
Yeah, exactly.
That's why I've added it to the verify method of the drivers.

**Comment by khanzadimahdi** [comment]
hmm, i have created `ReceiptInterface` in the Contracts path. have you seen it? i merge your pull request however i have created `ReceiptInterface` and in next version, payments will return that on successfully verifications.

**Comment by AramZahedi** [comment]
Test it first please. For ZarinPal it must be working, but test the other two please.

**Comment by khanzadimahdi** [comment]
ok. thanks for your contribution. i will add your name in next release.

**Comment by khanzadimahdi** [comment]
according to zarinpal docs: 
> Ref ID: A unique ID which is given to the customer whenever the transaction is done
successfully. This ID can be used for financial follow up.

**Pull request merged**
