### PR TITLE
Add description method

### PR DESCRIPTION
**Pull request by namvarii**
with this method, you can change the driver description on the fly

### CODE REVIEW

**Comment by khanzadimahdi** [comment]
hmmm, all drivers have description?
i think we dont need such method. there would be some drivers that never have any descriptions.
however you can change driver configs (description is a kind of config) on the fly using `config` method.

**Comment by khanzadimahdi** [comment]
can you fix paypal driver or create skrill driver?

**Comment by khanzadimahdi** [comment]
i want some body create the below drivers:

stripe
authorize
2checkout
braintree
skrill
payU
amazon payments
wepay
payoneer
paysimple
saderat
pasargad

thanks for your contribution.

**Comment by namvarii** [comment]
yes that true,
i'm using this method as ->description("SiteName #{$order->id}")
but i can even use ->config('description',"SiteName #{$order->id}")

now i'm dealing with one project, when i have time, try to create stripe or skrill  gateways.
thanks for good repo <3

**Comment by khanzadimahdi** [comment]
i close this pull request, we don't need a new method, you can use `config` method.
and we don't have `description` in all gateways, so your pull request can't be accepted.

thanks for your contribution.

**Pull request closed without merging**
