### PR TITLE
chinese docs

### PR DESCRIPTION
**Pull request by tu6ge**
## Description

add chinese docs.

## Motivation and context

I plan to add Payment institutions in China in the future

## How has this been tested?

No test required

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

**Comment by khanzadimahdi** [comment]
cool :smile:  I love it :heart: . 

can you add Chinese gateways to this package too?

**Comment by khanzadimahdi** [comment]
thanks for your contribution.

**Comment by tu6ge** [comment]
In the near future, I will add Chinese payment agencies

**Comment by khanzadimahdi** [comment]
> In the near future, I will add Chinese payment agencies

cool :gem:  thanks .

**Pull request merged**
